
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 48;
  public static final int LBRACKET = 40;
  public static final int MULT = 23;
  public static final int CHAR = 5;
  public static final int GE = 28;
  public static final int LPAREN = 38;
  public static final int SEMI = 36;
  public static final int INT = 4;
  public static final int MINUS = 22;
  public static final int RPAREN = 39;
  public static final int NOT = 20;
  public static final int AND = 18;
  public static final int INTLIT = 45;
  public static final int LT = 25;
  public static final int OR = 19;
  public static final int COMMA = 37;
  public static final int BOOL = 6;
  public static final int QMARK = 34;
  public static final int CLASS = 2;
  public static final int INC = 31;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int IF = 9;
  public static final int ID = 44;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 41;
  public static final int PRINTLINE = 14;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int EQEQ = 29;
  public static final int VOID = 8;
  public static final int FLOATLIT = 46;
  public static final int EQ = 33;
  public static final int ERROR = 49;
  public static final int CHARLIT = 47;
  public static final int COLON = 35;
  public static final int LBRACE = 42;
  public static final int ELSE = 10;
  public static final int READ = 12;
  public static final int FINAL = 3;
  public static final int WHILE = 11;
  public static final int FLOAT = 7;
  public static final int RBRACE = 43;
  public static final int NE = 30;
  public static final int DEC = 32;
  public static final int FALSE = 17;
  public static final int GT = 26;
  public static final int PRINT = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "FINAL",
  "INT",
  "CHAR",
  "BOOL",
  "FLOAT",
  "VOID",
  "IF",
  "ELSE",
  "WHILE",
  "READ",
  "PRINT",
  "PRINTLINE",
  "RETURN",
  "TRUE",
  "FALSE",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "LT",
  "GT",
  "LE",
  "GE",
  "EQEQ",
  "NE",
  "INC",
  "DEC",
  "EQ",
  "QMARK",
  "COLON",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "ID",
  "INTLIT",
  "FLOATLIT",
  "CHARLIT",
  "STRLIT",
  "ERROR"
  };
}

