import java.io.File;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.io.Reader;
import java_cup.runtime.Symbol;   // from CU

public class ScannerTest {

    public static void main(String[] args) {
        Reader reader = null;

        // Handle the file input vs stdin
        if (args.length == 1) {
            File input = new File(args[0]);
            if (!input.canRead()) {
                System.out.println("Error: could not read [" + input + "]");
                System.exit(1);
            }
            try {
                reader = new FileReader(input);
            } catch (Exception e) {
                e.printStackTrace();
                System.exit(1);
            }
        } else {
            reader = new InputStreamReader(System.in);
        }

        try {
            Lexer lexer = new Lexer(reader);   // this is generated by JFlex
            parser parser = new parser(lexer); // this is generated by CUP
            Program program = (Program) parser.parse().value; // AST root

            System.out.print(program.toString(0));  // this is the formatted AST
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

